### ISSUE TITLE
System.IO.FileNotFoundException: Could not find file "Util.SecureStorage".

### ISSUE THREAD

**Issue by jradesenv** [sameerkapps/SecureStorage#10]
Im getting that error in Samsung GT-19500 android 5.0, when app start and i call:
string jsonUser = CrossSecureStorage.Current.GetValue("current-user");

Event tried to set the SecurePassword in my splashscreen activity, but doesnt work.

Note: in my Moto G Android 6.0 it works with no error.

**Comment by sameerkapps** [comment]
It works in 6.0 and not in 5.0. It is hard to find the cause from here. Have you tried my sample app on both the phones? What are the results?

**Comment by jradesenv** [comment]
I think it's happening sometimes and maybe just in debug mode. Today, so far, the error has not shown. 
I'm using your library directly at app Initialize in app.cs. Maybe some libs aren't already loaded and the error is show

**Comment by sameerkapps** [comment]
This issue may be similar to 
https://github.com/sameerkapps/SecureStorage/issues/1

**Comment by sameerkapps** [comment]
Closing as there is no response.
