### ISSUE TITLE
what version of iOS is required to use this plugin?

### ISSUE THREAD

**Issue by CodeSpeak11** [sameerkapps/SecureStorage#15]
Working fine with 9.3.5 and later, but having potential issues with 8.4. Trying to determine which plugin is causing the problems

**Comment by sameerkapps** [comment]
I have tested it on iOS 9 and above. It should work on iOS 8.4; but I have not tested it. Were you able to figure out which one was causing the problem?

**Comment by sameerkapps** [comment]
Closing it since no response.
