### ISSUE TITLE
Access to secure storage while app is in background

### ISSUE THREAD

**Issue by CarlBartonSpok** [sameerkapps/SecureStorage#18]
Is it possible to setup SecureStorage to access data when the device is locked in response to a silent notification?

**Comment by sameerkapps** [comment]
It is pure API and does not require human interaction. So it should be possible. However, I have not tested it that way.

**Comment by CarlBartonSpok** [comment]
I did some additional research and it looks like for iOS the accessibility must be set at the record level using the Accessible property.

Something like this:

`
	var rec = new SecRecord(SecKind.GenericPassword)
        {
		Account = Keyboard,
		ValueData = NSData.FromString(val),
		Accessible = SecAccessible.AfterFirstUnlock
	};

`

I have not reviewed other platforms yet to see if there is anything similar but so far it only looks like iOS is the issue.

**Comment by sameerkapps** [comment]
Thanks @CarlBartonSpok. I used the tip in 2.5.0 to use SecAccessible.AfterFirstUnlock
 as default way to create a record. Cheers!
