### ISSUE TITLE
Android Password

### ISSUE THREAD

**Issue by rmenezes** [sameerkapps/SecureStorage#22]
Just for my knowledge, why we need to define a password for Android devices? Is this one thing that can be generated automatically to be more secure?

**Comment by cyrilcathala** [comment]
+1 on this one, it's a security leak!

I've found another plugin based on this one that has better password management: https://github.com/Aftnet/SecureStoragePlugin.

**Comment by sameerkapps** [comment]
Updated the latest version. Now in Android, the default password is the hardware serial number. But can be overridden. Please obfuscate the application, if you override it. Then it is not a security leak. Hope the new version helps.
