### ISSUE TITLE
Support backup accessibility keys for Keychain items

### ISSUE THREAD

**Issue by nmdias** [sameerkapps/SecureStorage#23]
As is, if a manual backup is made, without a password, an attacker can access the encrypted Keychain Items, and with some degree of effort, decrypt them. 

Adding support for the [kSecAttrAccessible](https://developer.apple.com/documentation/security/ksecattraccessible) key would allow to better restrict when a "keychain item is accessible."

Values you use with the kSecAttrAccessible attribute key.
- let kSecAttrAccessibleAfterFirstUnlock: CFString
  - The data in the keychain item cannot be accessed after a restart until the device has been unlocked once by the user.
- let kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly: CFString
  - The data in the keychain item cannot be accessed after a restart until the device has been unlocked once by the user.
- let kSecAttrAccessibleAlways: CFString
  - The data in the keychain item can always be accessed regardless of whether the device is locked.
let kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly: CFString
  - The data in the keychain can only be accessed when the device is unlocked. Only available if a passcode is set on the device.
- let kSecAttrAccessibleAlwaysThisDeviceOnly: CFString
  - The data in the keychain item can always be accessed regardless of whether the device is locked.
- let kSecAttrAccessibleWhenUnlocked: CFString
  - The data in the keychain item can be accessed only while the device is unlocked by the user.
- let kSecAttrAccessibleWhenUnlockedThisDeviceOnly: CFString
  - The data in the keychain item can be accessed only while the device is unlocked by the user.

Source: [Item Attribute Keys and Values](https://developer.apple.com/documentation/security/keychain_services/keychain_items/item_attribute_keys_and_values) 

Is it possible to add support for this?

Thank you.

**Comment by sameerkapps** [comment]
Done! 2.5.0 has support to set Accessibility. In AppDelegate, you can set "SecureStorageImplementation.DefaultAccessible". Hope that helps.
