### ISSUE TITLE
Can't get plugin to run on iOS

### ISSUE THREAD

**Issue by MonicaMarino** [sameerkapps/SecureStorage#27]
I followed the suggestions to set "Enable Keychain" in Entitlements.plist file, and to set "Custom Entitlements" to that .plist file.
The project won't build. I get this error:
**No valid iOP code signing kes found in keychain. You need to request a codesigning certificate from https://developer.apple.com**

I have the same problem when trying to run the sample code. I'm running Visual Studio for mac.
Any suggestions?

**Comment by sameerkapps** [comment]
The issue may be related to the signing certificate rather than the plugin. Could you build and run any other iOS apps? This link may help. https://developer.xamarin.com/guides/ios/getting_started/installation/device_provisioning/free-provisioning/
