### ISSUE TITLE
Sharing violation on path Util.SecureStorage

### ISSUE THREAD

**Issue by paradisehuman** [sameerkapps/SecureStorage#32]
Hi. In some devices like Galaxy Tab A 8.0,Galaxy J7,Galaxy J7 Neo, we got this error.

> SecureStorageImplementation.Save ()
> System.IO.IOException: Sharing violation on path Util.SecureStorage
> Sharing violation on path Util.SecureStorage
> System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x001b7] in <7822cfcead4342bf9d07f8ea73b8b0f8>:0
> System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean isAsync, System.Boolean anonymous) [0x00000] in <7822cfcead4342bf9d07f8ea73b8b0f8>:0
> System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.IsolatedStorage.IsolatedStorageFile isf) [0x0000a] in <7822cfcead4342bf9d07f8ea73b8b0f8>:0
> System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access) [0x00000] in <7822cfcead4342bf9d07f8ea73b8b0f8>:0
> (wrapper remoting-invoke-with-check) System.IO.IsolatedStorage.IsolatedStorageFileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess)
> SecureStorageImplementation.Save ()
> SecureStorageImplementation.SetValue (System.String key, System.String value)
> RestService+<RefreshToken>d__10.MoveNext ()
> ExceptionDispatchInfo.Throw ()
> TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
> TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
> TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task)
> TaskAwaiter`1[TResult].GetResult ()
> RestService+<PostAsync>d__4.MoveNext ()
> ExceptionDispatchInfo.Throw ()
> TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
> TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
> TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task)
> TaskAwaiter`1[TResult].GetResult ()
> GpsService+<PostLocationToServer>d__4.MoveNext ()
> ExceptionDispatchInfo.Throw ()
> TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
> TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
> TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task)
> TaskAwaiter`1[TResult].GetResult ()
> AppWorker+<PostWorkerLocationToServerAsync>d__6.MoveNext ()
> ExceptionDispatchInfo.Throw ()
> AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
> SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
> Thread+RunnableImplementor.Run ()
> IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
> (wrapper dynamic-method) System.Object:d15f67f7-51c1-48f3-8679-f75ffacb48dc (intptr,intptr)

**Comment by sameerkapps** [comment]
I have not tried those specific Android devices. But it works on most of the Android devices. Have you tried running the sample app on those devices? If the sample also fails then it would be device/fragmentation issue.

**Comment by paradisehuman** [comment]
@sameerkapps Infact when I Upgrade the nuget package from 1.2.2 to 2.0.0, I got this error on those devices.Is this problem fixed in 2.0.1 ?

**Comment by sameerkapps** [comment]
The only difference between 1.2.2 and 2.0.0 for Android is that it now has default password. The change in 2.01 is just the packaging structure. If the app runs on other devices but not on certain device(s), it can be due to differences in Android implementation (aka fragmentation).

**Comment by paradisehuman** [comment]
@sameerkapps It ran into problem in some situation, not always. It tries to store token , In 90% of situations everything working as expected , In some devices and in 10% of situations token is not saved and this exception throws.

**Comment by VictorBlomberg** [comment]
We have this problem on Android too. We've made a wrapper method that tries up to three times if an IOException is thrown. Not ideal, but works (one retry would probably be enough). We do have proper locking. We are running 2.0.1.

**Comment by sameerkapps** [comment]
With 2.5.0, there is a new way to store data securely using AndroidKeyStore. It will not interact with the file and avoid the issue. Let me know, if that works.
