### ISSUE TITLE
Error trying to set StoragePassword for Xamarin Forms UWP NETStandard 2.0

### ISSUE THREAD

**Issue by dfarrNTST** [sameerkapps/SecureStorage#33]
Hi, we are successfully using SecureStorage on Xamarin Forms Android and iOS, and we recently started working on a Xamarin Forms UWP app.  We have all of our Shared Code in the new templates using NETStandard 2.0, and when we try to set the StoragePassword in our UWP's App.xaml.cs file in the OnLaunched method, there isn't a StoragePassword property available to set.  The SecureStorageImplementation is there, but no properties show up.  We verified our references and NuGet packages are restored and resolved for this package and Xamarin Forms...the app runs fine when we comment out the StoragePassword code.

![xamarin uwp securestorage](https://user-images.githubusercontent.com/20890311/35626797-d561e444-0664-11e8-9919-82efc2b72516.png)

**Comment by sameerkapps** [comment]
Ver 2.0 does not need the password for UWP. The secure storage is implemented using the built-in password vault.
