### ISSUE TITLE
Not fully compatible with .NETStandard

### ISSUE THREAD

**Issue by rohitvipin** [sameerkapps/SecureStorage#34]
warning NU1701: Package 'sameerIOTApps.Plugin.SecureStorage 2.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by rodchenkov** [comment]
Same with my project

**Comment by sameerkapps** [comment]
Mea culpa. That was a bad packaging. Please get the latest version i.e. 2.0.1. Let me know if it solves the problem.

**Comment by Nico04** [comment]
For me the 2.0.1 version solves the problem, thanks !

**Comment by sameerkapps** [comment]
@Nico04 Glad to see that it worked for you.
