### ISSUE TITLE
iOS 10  - values not persisting

### ISSUE THREAD

**Issue by ronpf** [sameerkapps/SecureStorage#4]
After upgrading to iOS 10 (Xcode 8, iOS 10 simulators) 
values saved with CrossSecureStorage.Current.SetValue([key],[value]) are not persisting

**Comment by sameerkapps** [comment]
I have not tried with iOS 10. Will take a look (may take a few days.) In the meantime, should you find anything, please let the community know. Thx.

**Comment by EdHubbell** [comment]
Related to https://forums.xamarin.com/discussion/77760/ios-10-keychain

**Comment by sameerkapps** [comment]
Thanks for answering this Ed. With this I’ll close the issue.
