### ISSUE TITLE
Not working on iOS Simulator but works on iOS physical device

### ISSUE THREAD

**Issue by pmahend1** [sameerkapps/SecureStorage#44]
`var fooValue= CrossSecureStorage.Current.GetValue (“Foo”);` not working on iOS Simulator but works on iOS physical device.

**Comment by pakbaz** [comment]
this has been answered [https://github.com/sameerkapps/SecureStorage/issues/31#issuecomment-366205742](https://github.com/sameerkapps/SecureStorage/issues/31#issuecomment-366205742)

**Comment by pmahend1** [comment]
Yeah. had figured this out. forgot to update the issue. This can be closed.

**Comment by sameerkapps** [comment]
@pmahend1 & @pakbaz thanks for using the package. And @pakbaz I appreciate your answer.
