### ISSUE TITLE
System.NotImplementedException

### ISSUE THREAD

**Issue by MrLinDowsMac** [sameerkapps/SecureStorage#5]
After installed via NuGet, I try to run a project in Windows 8 or Android, and I get this: 

> System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

It does mean that is not available in PCL projects, only in shared?

**Comment by Bartmax** [comment]
Might be of interest: 

http://log.paulbetts.org/the-bait-and-switch-pcl-trick/

**Comment by dagostinelli** [comment]
This should be re-opened as a feature request.

**Comment by dagostinelli** [comment]
This lib cannot be easily used in a Xamarin Forms project as designed.  The bait and switch trick will give this lib some new life.
