### ISSUE TITLE
 New issue CrossSecureStorage not working in iOS

### ISSUE THREAD

**Issue by divyang4481** [sameerkapps/SecureStorage#8]
after resent update CrossSecureStorage is not able to save value through CrossSecureStorage plugin

**Comment by sameerkapps** [comment]
Is it same as https://github.com/sameerkapps/SecureStorage/issues/4?

**Comment by talhaa91** [comment]
not working after iOS 10 update. Are you aware of the issue and working on the fix?

**Comment by sameerkapps** [comment]
Closing since there is no response.
