### ISSUE TITLE
Key not saved/retrived on iOS 10 on simulator 

### ISSUE THREAD

**Issue by willsam100** [sameerkapps/SecureStorage#9]
Using your sample, I first this up on iOS 10 simulator, and the keys are not saved/retrieved. 

I debugged through the code, and no exceptions are being thrown. Using the nugget package in my work app, saving always returns false. 

steps:
enter values for key and value
press set key 
press get value

expected: value to be retrieved 
actual: no value is shown.

**Comment by sameerkapps** [comment]
The issue may be related to this:
https://forums.xamarin.com/discussion/77760/ios-10-keychain

**Comment by willsam100** [comment]
Thanks, I was able to get this working via this https://bugzilla.xamarin.com/show_bug.cgi?id=44361#c3 (not i did need to fiddle with some provisioning profiles and they are required to set the customer entitlements even though it's only running not the simulator).

**Comment by sameerkapps** [comment]
Good to see that it is working for you. Closing the issue.
